spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.user.datasource.url=jdbc:sqlserver://shop4me-mysql-server.database.windows.net:1433;database=private-user-data;user=shop4me-admin@shop4me-mysql-server;password=zmxncbv12345$;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.user.datasource.username=shop4me-admin
spring.user.datasource.password=zmxncbv12345$

spring.auctions.datasource.url=jdbc:sqlserver://shop4me-mysql-server.database.windows.net:1433;database=auction-data;user=shop4me-admin@shop4me-mysql-server;password=zmxncbv12345$;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.auctions.datasource.username=shop4me-admin
spring.auctions.datasource.password=zmxncbv12345$

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true